# Generated by Django 4.2.11 on 2024-05-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.productos'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
